// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartservice.grpc;

public final class GrpcProto {
  private GrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cartgateway_grpc_compiled_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cartgateway_grpc_compiled_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cartgateway_grpc_compiled_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cartgateway_grpc_compiled_Item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cartgateway_grpc_compiled_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cartgateway_grpc_compiled_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cartgateway_grpc_compiled_ListOfItems_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cartgateway_grpc_compiled_ListOfItems_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\035com.cartgateway.grpc.com" +
      "piled\"\\\n\005Order\022\016\n\006cartId\030\001 \001(\003\0222\n\005items\030" +
      "\002 \003(\0132#.com.cartgateway.grpc.compiled.It" +
      "em\022\017\n\007courier\030\003 \001(\t\"=\n\004Item\022\021\n\tproductId" +
      "\030\001 \001(\003\022\020\n\010quantity\030\002 \001(\003\022\020\n\010subTotal\030\003 \001" +
      "(\001\">\n\007Request\022\016\n\006cartId\030\001 \001(\003\022\021\n\tproduct" +
      "Id\030\002 \001(\003\022\020\n\010quantity\030\003 \001(\003\"A\n\013ListOfItem" +
      "s\0222\n\005items\030\001 \003(\0132#.com.cartgateway.grpc." +
      "compiled.Item2\201\004\n\013CartService\022a\n\taddToCa" +
      "rt\022&.com.cartgateway.grpc.compiled.Reque" +
      "st\032*.com.cartgateway.grpc.compiled.ListO" +
      "fItems\"\000\022d\n\014listAllItems\022&.com.cartgatew" +
      "ay.grpc.compiled.Request\032*.com.cartgatew" +
      "ay.grpc.compiled.ListOfItems\"\000\022b\n\ndelete" +
      "Item\022&.com.cartgateway.grpc.compiled.Req" +
      "uest\032*.com.cartgateway.grpc.compiled.Lis" +
      "tOfItems\"\000\022k\n\023updateItemOnTheCart\022&.com." +
      "cartgateway.grpc.compiled.Request\032*.com." +
      "cartgateway.grpc.compiled.ListOfItems\"\000\022" +
      "X\n\010checkOut\022$.com.cartgateway.grpc.compi" +
      "led.Order\032$.com.cartgateway.grpc.compile" +
      "d.Order\"\000B5\n&com.cartservice.grpc.genera" +
      "ted-sourcesB\tGrpcProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_cartgateway_grpc_compiled_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cartgateway_grpc_compiled_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cartgateway_grpc_compiled_Order_descriptor,
        new java.lang.String[] { "CartId", "Items", "Courier", });
    internal_static_com_cartgateway_grpc_compiled_Item_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cartgateway_grpc_compiled_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cartgateway_grpc_compiled_Item_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", "SubTotal", });
    internal_static_com_cartgateway_grpc_compiled_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_cartgateway_grpc_compiled_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cartgateway_grpc_compiled_Request_descriptor,
        new java.lang.String[] { "CartId", "ProductId", "Quantity", });
    internal_static_com_cartgateway_grpc_compiled_ListOfItems_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_cartgateway_grpc_compiled_ListOfItems_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cartgateway_grpc_compiled_ListOfItems_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
