// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartservice.grpc;

public interface ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cartgateway.grpc.compiled.Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int64 quantity = 2;</code>
   * @return The quantity.
   */
  long getQuantity();

  /**
   * <code>double subTotal = 3;</code>
   * @return The subTotal.
   */
  double getSubTotal();
}
