// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartservice.grpc;

public interface ListOfItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cartgateway.grpc.compiled.ListOfItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 1;</code>
   */
  java.util.List<com.cartservice.grpc.Item> 
      getItemsList();
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 1;</code>
   */
  com.cartservice.grpc.Item getItems(int index);
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 1;</code>
   */
  java.util.List<? extends com.cartservice.grpc.ItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 1;</code>
   */
  com.cartservice.grpc.ItemOrBuilder getItemsOrBuilder(
      int index);
}
