// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartservice.grpc;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cartgateway.grpc.compiled.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 cartId = 1;</code>
   * @return The cartId.
   */
  long getCartId();

  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  java.util.List<com.cartservice.grpc.Item> 
      getItemsList();
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  com.cartservice.grpc.Item getItems(int index);
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  java.util.List<? extends com.cartservice.grpc.ItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  com.cartservice.grpc.ItemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>string courier = 3;</code>
   * @return The courier.
   */
  java.lang.String getCourier();
  /**
   * <code>string courier = 3;</code>
   * @return The bytes for courier.
   */
  com.google.protobuf.ByteString
      getCourierBytes();
}
