// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartservice.grpc;

/**
 * Protobuf type {@code com.cartgateway.grpc.compiled.Order}
 */
public final class Order extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cartgateway.grpc.compiled.Order)
    OrderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Order.newBuilder() to construct.
  private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Order() {
    items_ = java.util.Collections.emptyList();
    courier_ = "";
  }

  @java.lang.Override
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Order();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Order(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            cartId_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<com.cartservice.grpc.Item>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(com.cartservice.grpc.Item.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            courier_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cartservice.grpc.GrpcProto.internal_static_com_cartgateway_grpc_compiled_Order_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cartservice.grpc.GrpcProto.internal_static_com_cartgateway_grpc_compiled_Order_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cartservice.grpc.Order.class, com.cartservice.grpc.Order.Builder.class);
  }

  public static final int CARTID_FIELD_NUMBER = 1;
  private long cartId_;
  /**
   * <code>int64 cartId = 1;</code>
   * @return The cartId.
   */
  @java.lang.Override
  public long getCartId() {
    return cartId_;
  }

  public static final int ITEMS_FIELD_NUMBER = 2;
  private java.util.List<com.cartservice.grpc.Item> items_;
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.cartservice.grpc.Item> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cartservice.grpc.ItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  @java.lang.Override
  public com.cartservice.grpc.Item getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
   */
  @java.lang.Override
  public com.cartservice.grpc.ItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int COURIER_FIELD_NUMBER = 3;
  private volatile java.lang.Object courier_;
  /**
   * <code>string courier = 3;</code>
   * @return The courier.
   */
  @java.lang.Override
  public java.lang.String getCourier() {
    java.lang.Object ref = courier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      courier_ = s;
      return s;
    }
  }
  /**
   * <code>string courier = 3;</code>
   * @return The bytes for courier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCourierBytes() {
    java.lang.Object ref = courier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      courier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cartId_ != 0L) {
      output.writeInt64(1, cartId_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(2, items_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(courier_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, courier_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cartId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, cartId_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, items_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(courier_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, courier_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cartservice.grpc.Order)) {
      return super.equals(obj);
    }
    com.cartservice.grpc.Order other = (com.cartservice.grpc.Order) obj;

    if (getCartId()
        != other.getCartId()) return false;
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getCourier()
        .equals(other.getCourier())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @SuppressWarnings("unchecked")
@java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCartId());
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + COURIER_FIELD_NUMBER;
    hash = (53 * hash) + getCourier().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cartservice.grpc.Order parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cartservice.grpc.Order parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cartservice.grpc.Order parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cartservice.grpc.Order parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cartservice.grpc.Order parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cartservice.grpc.Order parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cartservice.grpc.Order parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cartservice.grpc.Order parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cartservice.grpc.Order parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cartservice.grpc.Order parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cartservice.grpc.Order parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cartservice.grpc.Order parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cartservice.grpc.Order prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cartgateway.grpc.compiled.Order}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cartgateway.grpc.compiled.Order)
      com.cartservice.grpc.OrderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cartservice.grpc.GrpcProto.internal_static_com_cartgateway_grpc_compiled_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cartservice.grpc.GrpcProto.internal_static_com_cartgateway_grpc_compiled_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cartservice.grpc.Order.class, com.cartservice.grpc.Order.Builder.class);
    }

    // Construct using com.cartservice.grpc.Order.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cartId_ = 0L;

      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      courier_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cartservice.grpc.GrpcProto.internal_static_com_cartgateway_grpc_compiled_Order_descriptor;
    }

    @java.lang.Override
    public com.cartservice.grpc.Order getDefaultInstanceForType() {
      return com.cartservice.grpc.Order.getDefaultInstance();
    }

    @java.lang.Override
    public com.cartservice.grpc.Order build() {
      com.cartservice.grpc.Order result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @SuppressWarnings("unused")
	@java.lang.Override
    public com.cartservice.grpc.Order buildPartial() {
      com.cartservice.grpc.Order result = new com.cartservice.grpc.Order(this);
      int from_bitField0_ = bitField0_;
      result.cartId_ = cartId_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.courier_ = courier_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cartservice.grpc.Order) {
        return mergeFrom((com.cartservice.grpc.Order)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cartservice.grpc.Order other) {
      if (other == com.cartservice.grpc.Order.getDefaultInstance()) return this;
      if (other.getCartId() != 0L) {
        setCartId(other.getCartId());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (!other.getCourier().isEmpty()) {
        courier_ = other.courier_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cartservice.grpc.Order parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cartservice.grpc.Order) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long cartId_ ;
    /**
     * <code>int64 cartId = 1;</code>
     * @return The cartId.
     */
    @java.lang.Override
    public long getCartId() {
      return cartId_;
    }
    /**
     * <code>int64 cartId = 1;</code>
     * @param value The cartId to set.
     * @return This builder for chaining.
     */
    public Builder setCartId(long value) {
      
      cartId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cartId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCartId() {
      
      cartId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.cartservice.grpc.Item> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.cartservice.grpc.Item>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cartservice.grpc.Item, com.cartservice.grpc.Item.Builder, com.cartservice.grpc.ItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public java.util.List<com.cartservice.grpc.Item> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public com.cartservice.grpc.Item getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder setItems(
        int index, com.cartservice.grpc.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder setItems(
        int index, com.cartservice.grpc.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder addItems(com.cartservice.grpc.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder addItems(
        int index, com.cartservice.grpc.Item value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder addItems(
        com.cartservice.grpc.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder addItems(
        int index, com.cartservice.grpc.Item.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.cartservice.grpc.Item> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public com.cartservice.grpc.Item.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public com.cartservice.grpc.ItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public java.util.List<? extends com.cartservice.grpc.ItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public com.cartservice.grpc.Item.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.cartservice.grpc.Item.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public com.cartservice.grpc.Item.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.cartservice.grpc.Item.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cartgateway.grpc.compiled.Item items = 2;</code>
     */
    public java.util.List<com.cartservice.grpc.Item.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cartservice.grpc.Item, com.cartservice.grpc.Item.Builder, com.cartservice.grpc.ItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cartservice.grpc.Item, com.cartservice.grpc.Item.Builder, com.cartservice.grpc.ItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private java.lang.Object courier_ = "";
    /**
     * <code>string courier = 3;</code>
     * @return The courier.
     */
    public java.lang.String getCourier() {
      java.lang.Object ref = courier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string courier = 3;</code>
     * @return The bytes for courier.
     */
    public com.google.protobuf.ByteString
        getCourierBytes() {
      java.lang.Object ref = courier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string courier = 3;</code>
     * @param value The courier to set.
     * @return This builder for chaining.
     */
    public Builder setCourier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      courier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string courier = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCourier() {
      
      courier_ = getDefaultInstance().getCourier();
      onChanged();
      return this;
    }
    /**
     * <code>string courier = 3;</code>
     * @param value The bytes for courier to set.
     * @return This builder for chaining.
     */
    public Builder setCourierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      courier_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cartgateway.grpc.compiled.Order)
  }

  // @@protoc_insertion_point(class_scope:com.cartgateway.grpc.compiled.Order)
  private static final com.cartservice.grpc.Order DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cartservice.grpc.Order();
  }

  public static com.cartservice.grpc.Order getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Order>
      PARSER = new com.google.protobuf.AbstractParser<Order>() {
    @java.lang.Override
    public Order parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Order(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Order> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Order> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cartservice.grpc.Order getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

