// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartservice.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cartgateway.grpc.compiled.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 cartId = 1;</code>
   * @return The cartId.
   */
  long getCartId();

  /**
   * <code>int64 productId = 2;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int64 quantity = 3;</code>
   * @return The quantity.
   */
  long getQuantity();
}
