version: "3"

volumes:
  Databases:
    driver: 'local'

services:

  #######################################
  # KONG GATEWAY
  #######################################
  Kong-database:
    container_name: Kong-database
    image: postgres:9.6
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
      - ./kong_data:/var/lib/postgresql/data

  Kong-migrate:
    container_name: Kong-migrate
    image: kong/kong-gateway:2.8.0.0-alpine 
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=Kong-database
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
    links:
      - Kong-database
    depends_on:
      - Kong-database
    command: "kong migrations bootstrap"

  Kong-gateway:
    container_name: Kong-Gateway
    image: kong/kong-gateway:2.8.0.0-alpine
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=Kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    depends_on:
      - Kong-migrate
      - Kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong-gateway:8001"]
      interval: 5s
      timeout: 2s
      retries: 15

  ####################################### 
  # POC Microservices
  ####################################### 
  Product:
    container_name: POC-Product-Microservice
    restart: on-failure
    image: product
    build: .\POC-ProductMicroservice
    ports:
      - 8887:8887
    environment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://MySql:3306/poc?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 1234
      KAFKA_HOST: Kafka
      KAFKA_PORT: 9092
    depends_on:
      - Kafka
      - MySql

  Logger:
    container_name: POC-Logger-Microservice
    restart: on-failure
    image: logger
    build: .\POC-LoggerMicroservice
    ports:
      - 8888
    environment:
      MONGODB_HOST: Mongo
      MONGODB_USER: admin
      MONGODB_PASSWORD: 1234
      MONGODB_DATABASE: poc_logs
      MONGODB_PORT: 27017
      KAFKA_HOST: Kafka
      KAFKA_PORT: 9092
    depends_on:
      - Mongo
      - Kafka

  Cart-gateway:
    container_name: POC-Cart-Gateway-Microservice
    restart: on-failure
    image: cartgateway
    build: .\POC-CartGatewayMicroservice
    ports:
      - 8889:8889
    environment:
      GRPC-SERVER-PORT: 9999
      GRPC-SERVER-HOST: Cart-service
      PATH-TO-PRODUCT-MICROSERVICE: http://Product:8887/api/v1

  Cart-service:
    container_name: POC-Cart-Microservice
    restart: on-failure
    image: cart
    build: .\POC-CartMicroservice
    ports:
      - 8890
    environment:
      GRPC-SERVER-PORT: 9999
      SPRING_DATASOURCE_URL: jdbc:mysql://MySql:3306/poc?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      
    depends_on:
      - MySql
      - Product

  # ####################################### 
  # # Kafka
  # #######################################       
  Zookeeper:
    container_name: Zookeeper-server
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
   
  Kafka:
    container_name: Kafka-server
    image: 'bitnami/kafka:latest'
    ports:
      - 9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - Zookeeper

  # ####################################### 
  # # POC Databases
  # ####################################### 
  MySql:
    container_name: POC-Database_MySql
    image: mysql
    volumes: 
       - Databases:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: poc
      MYSQL_ROOT_PASSWORD: 1234

  Mongo:
    container_name: POC-Database_MongoDb
    image: mongo
    restart: on-failure
    volumes: 
       - Databases:/data/db
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234



    
