// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartgateway.servercomm.grpc;

public interface ProductDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cart.grpc.compiled.ProductDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string code = 4;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 4;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int64 quantity = 6;</code>
   * @return The quantity.
   */
  long getQuantity();

  /**
   * <code>double subTotal = 7;</code>
   * @return The subTotal.
   */
  double getSubTotal();
}
