// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cartgateway.servercomm.grpc;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cart.grpc.compiled.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
