server:
 port: 8887
 servlet:
  context-path: /api/v1

# Swagger Documentation Properties
springdoc:
  swagger-ui:
    path: /api-docs.html
  show-actuator: true
  default-consumes-media-type: application/json
  override-with-generic-response: true
  swagger-ui.tryItOutEnabled: true
  swagger-ui.disable-swagger-default-url: true
  swagger-ui.use-root-path: true

spring:
 #KAFKA
 kafka:
  producer:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
 #DATABASE
 datasource:
   url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/poc?autoReconnect=true&useSSL=false}
   username: ${MYSQL_USER:root}
   password: ${MYSQL_PASSWORD:1234}


#Actuator , exposing all endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
