// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cart.grpc.generated_sources;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cart.grpc.compiled.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.cart.grpc.compiled.ProductDetails items = 1;</code>
   */
  java.util.List<com.cart.grpc.generated_sources.ProductDetails> 
      getItemsList();
  /**
   * <code>repeated .com.cart.grpc.compiled.ProductDetails items = 1;</code>
   */
  com.cart.grpc.generated_sources.ProductDetails getItems(int index);
  /**
   * <code>repeated .com.cart.grpc.compiled.ProductDetails items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.cart.grpc.compiled.ProductDetails items = 1;</code>
   */
  java.util.List<? extends com.cart.grpc.generated_sources.ProductDetailsOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.cart.grpc.compiled.ProductDetails items = 1;</code>
   */
  com.cart.grpc.generated_sources.ProductDetailsOrBuilder getItemsOrBuilder(
      int index);
}
