
spring:
   datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/poc?autoReconnect=true&useSSL=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:1234}
    
    #Actuator , exposing all endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
grpc:
  server:
    port: 80