
server:
  port: 8888

spring:
   datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/poc?autoReconnect=true&useSSL=false}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:1234}