
# Server Properties
server:
 port: 8889
 servlet:
  context-path: /api/v1
 forward-headers-strategy: FRAMEWORK #--> https://springdoc.org/#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

# Actuator Properties , exposing all endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

       
# Swagger Documentation Properties
springdoc:
  swagger-ui:
    path: /api-docs.html
  default-consumes-media-type: application/json
  swagger-ui.tryItOutEnabled: true
# To disable the swagger-ui default petstore url
  swagger-ui.disable-swagger-default-url: true 
  swagger-ui.use-root-path: true
#    config-url: 
#  show-login-endpoint: true
  show-actuator: true


#LOGGING PROPERTIES
# Empty this property to disable console logging
#logging:
#  pattern:
#    console: 
#
## Specify the path to the main log file so you will still have your logs somewhere
#  file:
#    name: ./src/main/resources/Logs.log

  