// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.cart.grpc.generated_sources;

public final class GrpcProto {
  private GrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cart_grpc_compiled_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cart_grpc_compiled_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cart_grpc_compiled_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cart_grpc_compiled_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cart_grpc_compiled_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cart_grpc_compiled_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cart_grpc_compiled_ProductDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cart_grpc_compiled_ProductDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cart_grpc_compiled_StringResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cart_grpc_compiled_StringResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\026com.cart.grpc.compiled\"\030" +
      "\n\004User\022\020\n\010username\030\001 \001(\t\"^\n\007Request\022.\n\010u" +
      "sername\030\001 \001(\0132\034.com.cart.grpc.compiled.U" +
      "ser\022\021\n\tproductId\030\002 \001(\003\022\020\n\010quantity\030\003 \001(\003" +
      "\"E\n\014ListResponse\0225\n\005items\030\001 \003(\0132&.com.ca" +
      "rt.grpc.compiled.ProductDetails\"r\n\016Produ" +
      "ctDetails\022\021\n\tproductId\030\001 \001(\003\022\014\n\004name\030\002 \001" +
      "(\t\022\014\n\004code\030\004 \001(\t\022\r\n\005price\030\005 \001(\001\022\020\n\010quant" +
      "ity\030\006 \001(\003\022\020\n\010subTotal\030\007 \001(\001\"\037\n\014StringRes" +
      "ult\022\017\n\007message\030\001 \001(\t2\341\002\n\013CartService\022T\n\t" +
      "addToCart\022\037.com.cart.grpc.compiled.Reque" +
      "st\032$.com.cart.grpc.compiled.ListResponse" +
      "\"\000\022S\n\013getAllItems\022\034.com.cart.grpc.compil" +
      "ed.User\032$.com.cart.grpc.compiled.ListRes" +
      "ponse\"\000\022U\n\nremoveItem\022\037.com.cart.grpc.co" +
      "mpiled.Request\032$.com.cart.grpc.compiled." +
      "ListResponse\"\000\022P\n\010checkOut\022\034.com.cart.gr" +
      "pc.compiled.User\032$.com.cart.grpc.compile" +
      "d.StringResult\"\000B.\n\037com.cart.grpc.genera" +
      "ted_sourcesB\tGrpcProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_cart_grpc_compiled_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cart_grpc_compiled_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cart_grpc_compiled_User_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_cart_grpc_compiled_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cart_grpc_compiled_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cart_grpc_compiled_Request_descriptor,
        new java.lang.String[] { "Username", "ProductId", "Quantity", });
    internal_static_com_cart_grpc_compiled_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_cart_grpc_compiled_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cart_grpc_compiled_ListResponse_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_com_cart_grpc_compiled_ProductDetails_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_cart_grpc_compiled_ProductDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cart_grpc_compiled_ProductDetails_descriptor,
        new java.lang.String[] { "ProductId", "Name", "Code", "Price", "Quantity", "SubTotal", });
    internal_static_com_cart_grpc_compiled_StringResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_cart_grpc_compiled_StringResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cart_grpc_compiled_StringResult_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
